name: Deploy to SFTP Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install lftp and ssh-keyscan
      run: |
        sudo apt-get install -y lftp openssh-client

    - name: Add SFTP server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts

    - name: Upload files to SFTP server
      run: |
        lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} sftp://${{ secrets.FTP_SERVER }}:22 -e "
          mirror -R ./ /
          quit
        "
